### ISSUE TITLE
Images with spaces in the file name no longer work

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux-sdk-builder#324] opened 2020-09-03 18:49 UTC
The image displayed with `"@skyux-sdk/builder": "4.3.0"` but fail to load with a 404 with `"@skyux-sdk/builder": "4.5.0"` (latest) after running `skyux upgrade`.

I'm not positive it's a builder issue since other packages updated as well, but the `skyux-lib-media` version has not changed for months.

```html
      <sky-image
        imageSource="~/assets/img/swagger/Operation ID.png"
        caption="I am the caption now"
        ></sky-image>
```

I checked my `dist/assets` folder and the images are there with spaces in the name.

Old dependencies:
```json
  "dependencies": {
    "@angular/animations": "9.1.12",
    "@angular/common": "9.1.12",
    "@angular/compiler": "9.1.12",
    "@angular/core": "9.1.12",
    "@angular/forms": "9.1.12",
    "@angular/platform-browser": "9.1.12",
    "@angular/platform-browser-dynamic": "9.1.12",
    "@angular/router": "9.1.12",
    "@blackbaud/auth-client": "2.30.0",
    "@blackbaud/skyux-builder-plugin-auth-email-whitelist": "2.0.1",
    "@blackbaud/skyux-lib-clipboard": "4.0.0",
    "@blackbaud/skyux-lib-code-block": "4.0.0",
    "@blackbaud/skyux-lib-media": "4.0.0",
    "@blackbaud/skyux-lib-restricted-view": "4.1.0",
    "@blackbaud/skyux-lib-stache": "4.2.1",
    "@skyux/animations": "4.0.1",
    "@skyux/assets": "4.0.1",
    "@skyux/config": "4.0.2",
    "@skyux/core": "4.1.0",
    "@skyux/forms": "4.6.0",
    "@skyux/http": "4.0.0",
    "@skyux/i18n": "4.0.1",
    "@skyux/indicators": "4.2.0",
    "@skyux/layout": "4.2.2",
    "@skyux/lookup": "4.2.1",
    "@skyux/modals": "4.5.0",
    "@skyux/omnibar-interop": "4.0.0",
    "@skyux/popovers": "4.2.0",
    "@skyux/router": "4.0.0",
    "@skyux/tabs": "4.3.0",
    "@skyux/theme": "4.8.0",
    "rxjs": "6.6.2",
    "zone.js": "0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "9.1.12",
    "@blackbaud/skyux-builder-plugin-code-block": "1.1.0",
    "@blackbaud/skyux-builder-plugin-stache": "2.0.3",
    "@skyux-sdk/builder": "4.3.0",
    "@skyux-sdk/e2e": "4.0.0",
    "@skyux-sdk/testing": "4.0.0",
    "codelyzer": "5.2.2",
    "ts-node": "8.3.0",
    "tslint": "6.1.3",
    "typescript": "3.8.3"
  }
```

New dependencies:
```json
  "dependencies": {
    "@angular/animations": "9.1.12",
    "@angular/common": "9.1.12",
    "@angular/compiler": "9.1.12",
    "@angular/core": "9.1.12",
    "@angular/forms": "9.1.12",
    "@angular/platform-browser": "9.1.12",
    "@angular/platform-browser-dynamic": "9.1.12",
    "@angular/router": "9.1.12",
    "@blackbaud/auth-client": "2.33.0",
    "@blackbaud/skyux-builder-plugin-auth-email-whitelist": "2.0.1",
    "@blackbaud/skyux-lib-clipboard": "4.0.0",
    "@blackbaud/skyux-lib-code-block": "4.0.1",
    "@blackbaud/skyux-lib-media": "4.0.0",
    "@blackbaud/skyux-lib-restricted-view": "4.1.0",
    "@blackbaud/skyux-lib-stache": "4.2.1",
    "@skyux/animations": "4.0.1",
    "@skyux/assets": "4.0.1",
    "@skyux/config": "4.0.3",
    "@skyux/core": "4.3.0",
    "@skyux/forms": "4.9.0",
    "@skyux/http": "4.0.1",
    "@skyux/i18n": "4.0.1",
    "@skyux/indicators": "4.2.0",
    "@skyux/layout": "4.2.3",
    "@skyux/lookup": "4.3.0",
    "@skyux/modals": "4.5.0",
    "@skyux/omnibar-interop": "4.0.1",
    "@skyux/popovers": "4.2.1",
    "@skyux/router": "4.0.1",
    "@skyux/tabs": "4.3.2",
    "@skyux/theme": "4.10.2",
    "rxjs": "6.6.2",
    "zone.js": "0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "9.1.12",
    "@blackbaud/skyux-builder-plugin-code-block": "1.1.0",
    "@blackbaud/skyux-builder-plugin-stache": "2.0.3",
    "@skyux-sdk/builder": "4.5.0",
    "@skyux-sdk/e2e": "4.0.0",
    "@skyux-sdk/testing": "4.1.0",
    "codelyzer": "5.2.2",
    "ts-node": "8.3.0",
    "tslint": "6.1.3",
    "typescript": "3.8.3"
  }
```

**Comment by Blackbaud-BobbyEarl** [comment] 2020-09-03 21:52
FYI... I worked with @Blackbaud-ChristiSchneider and @Blackbaud-TerryHelems to debug as I was unable to duplicate the issue using `@skyux-sdk/builder`.

We then were able to determine the issue was localized to using our CDN Origin service, so I'm going to close this issue as we're tracking it internally.

FWIW, our use of implicit conversion of `PathString` to `String` and https://github.com/dotnet/aspnetcore/commit/caf4374f836de0fb973f1165aa7221112ea598bf#diff-6d518aec2e8294d29a2c5a46dfa6d74c seems to be the root cause.

**Closed by Blackbaud-BobbyEarl** 2020-09-03 21:52 UTC
